nombr_Produ = input("")
costo_unita = input("")
preci_venta = input("")
canti_unida = input("")
ganancia = (int(preci_venta)-int(costo_unita))*int(canti_unida)
print(f"Producto: {nombr_Produ}")
print(f"CU: ${costo_unita}")
print(f"PVP: ${preci_venta}")
print(f"Unidades Disponibles: {canti_unida}")
print(f"Ganancia: ${ganancia}")
